name: Scrape

on:
  schedule:
    - cron: "*/5 * * * *"


jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pip install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install --python `which python`
    - name: Install libraries
      run: |-
    - run: cd Code && pip install requests
    - run: cd Code && pip install bs4
    - run: cd Code && pip install pandas
    - run: cd Code && pip install numpy
    - name: Run scraper
      run: cd Code && python scrape.py
    - name: Slack Notification
      uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Hello, Slack!
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
