name: Scrape

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pip install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install --python `which python`
    - name: Install libraries
      run: |-
    - run: cd Code && pip install requests
    - run: cd Code && pip install bs4
    - run: cd Code && pip install pandas
    - run: cd Code && pip install numpy
    - name: Run scraper
      run: cd Code && python scrape.py
